#!/usr/bin/env bash
# installs and configures nginx

sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
