#!/usr/bin/env bash
# configures custom 404 page

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo mkdir -p /var/www/html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_error.html > /dev/null

old_block="server_name _;"
new_block="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v\=SsoOG6ZeyUI;\n\t}\n\n\terror_page 404 \/custom_error.html;\n\tlocation = \/custom_error.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/$old_block/$new_block/" /etc/nginx/sites-available/default

sudo service nginx start
