#!/usr/bin/env bash
# Installs and configures HAproxy on load balancer server

if ! command -v haproxy &>/dev/null
then
	sudo apt-get update
	sudo apt-get install haproxy -y
fi

echo -e "frontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 266041-web-01 54.160.123.234:80 check\n\tserver 266041-web-02 54.161.236.101:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
