#!/usr/bin/env bash
# manages manage_my_process i.e. starts, stops and restarts manage_my_process

start ()
{
	./manage_my_process &
	echo "$!" > "/var/run/my_process.pid"
}

stop ()
{
	bak_pid="$(cat /var/run/my_process.pid)"
	sudo kill -TERM "$bak_pid"
	rm -f /var/run/my_process.pid
}

if [ "$1" = "start" ]
then
	start
	echo "manage_my_process started"
elif [ "$1" = "stop" ]
then
	stop
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]
then
	stop
	start
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
