#!/usr/bin/env bash
# displays Best School 10 times, but displays Best School and then Hi on a new line on the 9th iteration
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	fi
	((i++))
done
