#!/usr/bin/env bash
# a script that configures a container to specific requirements

sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill -f apache2
sudo service nginx restart
